/**
 * Demo data lifted from the prototype, so both clients render recognisable
 * content on first run rather than an empty state.
 */

export const CATEGORIES = [
  { name: 'Electrician', nameGu: 'ઇલેક્ટ્રિશિયન', sortOrder: 1 },
  { name: 'Welder', nameGu: 'વેલ્ડર', sortOrder: 2 },
  { name: 'Helper', nameGu: 'હેલ્પર', sortOrder: 3 },
  { name: 'Fitter', nameGu: 'ફિટર', sortOrder: 4 },
  { name: 'Plumber', nameGu: 'પ્લમ્બર', sortOrder: 5 },
  { name: 'Technician', nameGu: 'ટેકનિશિયન', sortOrder: 6 },
];

export const EMPLOYEES = [
  {
    employeeCode: 'EMP-1047',
    name: 'Ramesh Patel',
    mobile: '+919876543210',
    age: 32,
    experienceBand: '5-10' as const,
    category: 'Electrician',
    presentSalary: 18000,
    expectedSalary: 25000,
    currentOrganization: null,
    history: [
      { company: 'Welspun Corp', from: '2024-01', to: '2025-03' },
      { company: 'Reliance Industries', from: '2021-06', to: '2023-12' },
    ],
  },
  {
    employeeCode: 'EMP-0982',
    name: 'Vikas Joshi',
    mobile: '+919824511270',
    age: 29,
    experienceBand: '3-5' as const,
    category: 'Welder',
    presentSalary: 22000,
    expectedSalary: 30000,
    currentOrganization: 'Reliance Industries',
    history: [{ company: 'Adani Group', from: '2020-04', to: '2022-11' }],
  },
  {
    employeeCode: 'EMP-1124',
    name: 'Arjun Solanki',
    mobile: '+919033214422',
    age: 26,
    experienceBand: '1-3' as const,
    category: 'Plumber',
    presentSalary: 15000,
    expectedSalary: 20000,
    currentOrganization: null,
    history: [],
  },
  {
    employeeCode: 'EMP-0651',
    name: 'Pradeep Sharma',
    mobile: '+919982033421',
    age: 24,
    experienceBand: '0-1' as const,
    category: 'Helper',
    presentSalary: 12000,
    expectedSalary: 16000,
    currentOrganization: 'Birla Group',
    history: [],
  },
  {
    employeeCode: 'EMP-0814',
    name: 'Bhavesh Rana',
    mobile: '+919898911226',
    age: 41,
    experienceBand: '10+' as const,
    category: 'Fitter',
    presentSalary: 32000,
    expectedSalary: 40000,
    currentOrganization: 'L&T Construction',
    history: [{ company: 'JSW Steel', from: '2015-02', to: '2021-08' }],
  },
  // Deliberately code-less: reproduces the prototype's "— Pending —" row and
  // keeps the "Codes to Assign" queue non-empty.
  {
    employeeCode: null,
    name: 'Sagar Patel',
    mobile: '+917984211003',
    age: 28,
    experienceBand: '3-5' as const,
    category: 'Electrician',
    presentSalary: 19000,
    expectedSalary: 24000,
    currentOrganization: null,
    history: [],
  },
  {
    employeeCode: 'EMP-1201',
    name: 'Suresh Kumar',
    mobile: '+919822011242',
    age: 27,
    experienceBand: '1-3' as const,
    category: 'Helper',
    presentSalary: 13000,
    expectedSalary: 17000,
    currentOrganization: 'Tata Motors',
    history: [],
  },
  {
    employeeCode: 'EMP-1218',
    name: 'Manish Vyas',
    mobile: '+919725611820',
    age: 31,
    experienceBand: '3-5' as const,
    category: 'Welder',
    presentSalary: 21000,
    expectedSalary: 28000,
    currentOrganization: null,
    history: [],
  },
  {
    employeeCode: 'EMP-1233',
    name: 'Dinesh Kumar',
    mobile: '+919988035441',
    age: 25,
    experienceBand: '0-1' as const,
    category: 'Helper',
    presentSalary: 12000,
    expectedSalary: 15000,
    currentOrganization: 'Birla Group',
    history: [],
  },
  {
    employeeCode: 'EMP-1240',
    name: 'Jignesh Patel',
    mobile: '+919898122634',
    age: 35,
    experienceBand: '5-10' as const,
    category: 'Fitter',
    presentSalary: 26000,
    expectedSalary: 34000,
    currentOrganization: 'L&T Construction',
    history: [],
  },
  {
    employeeCode: 'EMP-1255',
    name: 'Naresh Bhatt',
    mobile: '+919725611821',
    age: 30,
    experienceBand: '3-5' as const,
    category: 'Welder',
    presentSalary: 23000,
    expectedSalary: 29000,
    currentOrganization: 'Reliance Industries',
    history: [],
  },
  {
    employeeCode: 'EMP-1262',
    name: 'Hardik Mehta',
    mobile: '+919033214423',
    age: 33,
    experienceBand: '5-10' as const,
    category: 'Fitter',
    presentSalary: 25000,
    expectedSalary: 32000,
    currentOrganization: 'L&T Construction',
    history: [],
  },
];

export const JOBS = [
  {
    title: 'Senior Electrician',
    company: 'Tata Motors',
    location: 'GIDC Baroda',
    category: 'Electrician',
    experienceBand: '5-10' as const,
    joiningUrgency: 'immediate' as const,
    salaryMin: 22000,
    salaryMax: 28000,
    description:
      "Tata Motors GIDC Baroda is hiring experienced electricians for the new vehicle assembly line. You'll be responsible for installation, troubleshooting, and maintenance of industrial electrical systems including panel wiring, motor controls, and PLC-based machinery.",
    requirements: [
      'ITI Electrician certificate (mandatory)',
      '5+ years industrial wiring experience',
      'Familiarity with 3-phase systems and motor controls',
      'Safety compliance training preferred',
    ],
    referralReward: 2500,
    tenureMonths: 3,
    notifyCase: 1 as const,
    status: 'active' as const,
    postedHoursAgo: 2,
  },
  {
    title: 'Welder (MIG/TIG)',
    company: 'Reliance Industries',
    location: 'Jamnagar',
    category: 'Welder',
    experienceBand: '3-5' as const,
    joiningUrgency: '15_days' as const,
    salaryMin: 24000,
    salaryMax: 32000,
    description:
      'Reliance Jamnagar refinery requires certified MIG/TIG welders for structural and pipeline fabrication work. Shift-based roles with accommodation provided.',
    requirements: [
      'ITI Welder certificate',
      '3+ years MIG/TIG experience',
      'Ability to read fabrication drawings',
      'Valid safety training certificate',
    ],
    referralReward: 3000,
    tenureMonths: 3,
    notifyCase: 2 as const,
    status: 'active' as const,
    postedHoursAgo: 24,
  },
  {
    title: 'Helper (Production Floor)',
    company: 'Birla Group',
    location: 'Vadodara',
    category: 'Helper',
    experienceBand: '0-1' as const,
    joiningUrgency: 'immediate' as const,
    salaryMin: 14000,
    salaryMax: 16000,
    description:
      'Entry-level production floor helpers needed for the Vadodara manufacturing unit. Full training provided. Ideal for candidates starting their industrial career.',
    requirements: [
      'Minimum 10th standard pass',
      'Willing to work in shifts',
      'Physically fit for floor work',
    ],
    referralReward: 2500,
    tenureMonths: 3,
    notifyCase: 3 as const,
    status: 'active' as const,
    postedHoursAgo: 72,
  },
  {
    title: 'Fitter (Pipe & Structure)',
    company: 'L&T Construction',
    location: 'Surat',
    category: 'Fitter',
    experienceBand: '5-10' as const,
    joiningUrgency: '30_days' as const,
    salaryMin: 26000,
    salaryMax: 34000,
    description:
      'L&T Construction is hiring experienced pipe and structural fitters for a large infrastructure project in Surat. Long-term project with overtime opportunities.',
    requirements: [
      'ITI Fitter certificate',
      '5+ years pipe fitting experience',
      'Experience with structural alignment and fabrication',
    ],
    referralReward: 5000,
    tenureMonths: 6,
    notifyCase: 1 as const,
    status: 'active' as const,
    postedHoursAgo: 120,
  },
  {
    title: 'Plumber (Industrial)',
    company: 'Adani Group',
    location: 'Mundra',
    category: 'Plumber',
    experienceBand: '3-5' as const,
    joiningUrgency: '15_days' as const,
    salaryMin: 20000,
    salaryMax: 26000,
    description:
      'Industrial plumbing role at the Adani Mundra port facility. Maintenance and installation of water, drainage and process piping systems.',
    requirements: ['ITI Plumber certificate', '3+ years industrial plumbing experience'],
    referralReward: 3500,
    tenureMonths: 3,
    notifyCase: 2 as const,
    status: 'closing' as const,
    postedHoursAgo: 168,
  },
  {
    title: 'Maintenance Technician',
    company: 'JSW Steel',
    location: 'Ahmedabad',
    category: 'Technician',
    experienceBand: '1-3' as const,
    joiningUrgency: 'immediate' as const,
    salaryMin: 18000,
    salaryMax: 23000,
    description:
      'Preventive and breakdown maintenance of plant machinery at the JSW Ahmedabad facility.',
    requirements: ['ITI in any mechanical trade', '1+ year maintenance experience'],
    referralReward: 2500,
    tenureMonths: 3,
    notifyCase: 2 as const,
    status: 'draft' as const,
    postedHoursAgo: null,
  },
];

/**
 * Applications spanning every pipeline stage, so the admin board and the
 * dashboard funnel both have something real to render.
 */
export const APPLICATIONS = [
  { employee: 'Ramesh Patel', job: 'Senior Electrician', status: 'shortlisted' as const, daysAgo: 0, interviewInDays: 3, interviewLocation: 'Gate 3, GIDC' },
  { employee: 'Manish Vyas', job: 'Welder (MIG/TIG)', status: 'applied' as const, daysAgo: 1 },
  { employee: 'Dinesh Kumar', job: 'Helper (Production Floor)', status: 'hired' as const, daysAgo: 14, hiredDaysAgo: 13 },
  { employee: 'Jignesh Patel', job: 'Fitter (Pipe & Structure)', status: 'hired' as const, daysAgo: 200, hiredDaysAgo: 190 },
  { employee: 'Arjun Solanki', job: 'Plumber (Industrial)', status: 'shortlisted' as const, daysAgo: 5 },
  { employee: 'Suresh Kumar', job: 'Senior Electrician', status: 'applied' as const, daysAgo: 2 },
  { employee: 'Pradeep Sharma', job: 'Senior Electrician', status: 'interview' as const, daysAgo: 7, interviewInDays: 5, interviewLocation: 'HR Office, Baroda' },
  { employee: 'Bhavesh Rana', job: 'Helper (Production Floor)', status: 'interview' as const, daysAgo: 6, interviewInDays: 6, interviewLocation: 'Plant Gate 1' },
  { employee: 'Naresh Bhatt', job: 'Welder (MIG/TIG)', status: 'hired' as const, daysAgo: 220, hiredDaysAgo: 214 },
  { employee: 'Hardik Mehta', job: 'Fitter (Pipe & Structure)', status: 'hired' as const, daysAgo: 260, hiredDaysAgo: 250 },
  { employee: 'Vikas Joshi', job: 'Welder (MIG/TIG)', status: 'rejected' as const, daysAgo: 21, rejectionReason: 'Certification missing' },
];

/**
 * Referrals covering the whole lifecycle: one mid-tenure, one long overdue so
 * the very first cron run produces a pending reward, one already paid, and two
 * still early in the funnel.
 */
export const REFERRALS = [
  {
    referrer: 'Ramesh Patel',
    friendName: 'Suresh Kumar',
    friendMobile: '+919822011242',
    job: 'Senior Electrician',
    status: 'tenure_running' as const,
    hiredDaysAgo: 13,
    tenureMonths: 3,
    rewardAmount: 2500,
  },
  {
    referrer: 'Vikas Joshi',
    friendName: 'Naresh Bhatt',
    friendMobile: '+919725611821',
    job: 'Welder (MIG/TIG)',
    // Past due on purpose — the first `npm run tenure:run` turns this into a
    // pending reward, which is the whole flow in one command.
    status: 'tenure_running' as const,
    hiredDaysAgo: 214,
    tenureMonths: 3,
    rewardAmount: 3000,
  },
  {
    referrer: 'Pradeep Sharma',
    friendName: 'Hardik Mehta',
    friendMobile: '+919033214423',
    job: 'Fitter (Pipe & Structure)',
    status: 'tenure_running' as const,
    hiredDaysAgo: 250,
    tenureMonths: 6,
    rewardAmount: 5000,
  },
  {
    referrer: 'Ramesh Patel',
    friendName: 'Dinesh Kumar',
    friendMobile: '+919988035441',
    job: 'Helper (Production Floor)',
    status: 'rewarded' as const,
    hiredDaysAgo: 310,
    tenureMonths: 3,
    rewardAmount: 2500,
    paid: true,
  },
  {
    referrer: 'Bhavesh Rana',
    friendName: 'Pinkesh Mistry',
    friendMobile: '+919898122635',
    job: 'Fitter (Pipe & Structure)',
    status: 'shortlisted' as const,
    tenureMonths: 6,
    rewardAmount: 5000,
  },
  {
    referrer: 'Arjun Solanki',
    friendName: 'Sagar Vyas',
    friendMobile: '+919033214424',
    job: 'Senior Electrician',
    status: 'pending' as const,
    tenureMonths: 3,
    rewardAmount: 2500,
  },
  {
    referrer: 'Ramesh Patel',
    friendName: 'Kapil Trivedi',
    friendMobile: '+919988035442',
    job: null,
    status: 'pending' as const,
    tenureMonths: 3,
    rewardAmount: 2500,
  },
];
